import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../../../globals.css";
import DesktopMemberNavbar from "@/components/dashboard/member/desktop/DesktopMemberNavbar";
import { ToastProvider } from "@/components/hooks/use-toast";
import MemberBottomNavbar from "@/components/navbar/member/MemberBottomNavbar";
import DesktopMemberDashboardSidebar from "@/components/sidebar/member/desktop/DesktopSidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "ELITEFIT | Welcome to your fitness journey",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-green-300 antialiased `}
      >
        <ToastProvider />
        <div className="min-h-screen bg-gray-50 ">
          <div className="hidden md:block h-screen  ">
            <DesktopMemberNavbar />
            <div className="flex  h-[calc(100vh-64px)]">
              <DesktopMemberDashboardSidebar />
              <main className="w-full overflow-auto">{children}</main>
            </div>
          </div>

          <div className="block md:hidden pb-12 no-scrollbar">
            {children}
            <MemberBottomNavbar />
          </div>
        </div>
      </body>
    </html>
  );
}
