import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../../../globals.css";
import { ToastProvider } from "@/components/hooks/use-toast";
import OwnerNavbar from "@/components/navbar/owner/OwnerNavbar";
import Sidebar from "@/components/sidebar/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "EliteFit",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen overflow-hidden`}
      >
        <ToastProvider />
        <OwnerNavbar />
        <div className="flex  h-[calc(100vh-64px)]">
          {/* Sidebar Fixed */}
          <Sidebar />

          {/* Main Content Scrollable */}
          <main className="w-full overflow-auto">{children}</main>
        </div>
      </body>
    </html>
  );
}
